### ISSUE TITLE
PSOC PWM is not working

### ISSUE THREAD

**Issue by ryanvade** [SIUE-SIGR/KIPR-Open#1]
When testing PSOC motor/servo controls we noticed that the frequency is changing not the width of the pulses.  Motor/Servo control is not working at the moment.

**Comment by BryanOrabutt** [comment]
Just for clarification: what are you sending to the PSoC to change motor speed/servo position?

**Comment by ryanvade** [comment]
We tested move and set servo position. For example:

```
a5\a
```

During testing, we sent the commands over with cutecom set to hex input.  

```
61 35 07
```

The serial responses were as they should be but the scope showed otherwise.

**Comment by ryanvade** [comment]
@Zabot would you like to chime in?

**Comment by BryanOrabutt** [comment]
And you're using the most recent commit on the psoc-code branch?

**Comment by ryanvade** [comment]
I pulled it before flashing the PSOC.

**Comment by BryanOrabutt** [comment]
Ok, I'll pull it and take a look.

**Comment by BryanOrabutt** [comment]
What is the encoder resolution per tick? For now I'm just putting a placeholder but to calculate velocity I'll need the real value.

For now ignore the MAV command as I have not figured out a good way to write this function PSoC side. Use the MOV command to set the PWMs directly to change speed:

b[Pulse width][bel]
where Pulse Width is an integer between 0 and 255 (off, full speed), and bel is the ASCII bell character 0x07.

Servo stuff looks fine to me, I can't see why it was giving you issues. Can you give details on your setup?

**Comment by ryanvade** [comment]
We were unable to get any form of motor/servo control last time we tested.

**Comment by ryanvade** [comment]
Possibly fixed with commit 465c8
