### ISSUE TITLE
Starting the bots

### ISSUE THREAD

**Issue by ryanvade** [SIUE-SIGR/KIPR-Open#3]
When we put both bots on the game board, they should be started with the light just like Botball correct?  If so, how are we going to do that?  Should we setup a button that starts the program waiting for the light?

**Comment by BryanOrabutt** [comment]
We have a whole set of analog blocks to use on the PSoC and unused MISC pins that can be routed to them. A simple ADC with a light sensor would not be hard to implement for this. I'll get on it this weekend.

**Comment by BryanOrabutt** [comment]
Code has been started on light sensor integration. I'll close this issue once the code is known to be working.

**Comment by ryanvade** [comment]
We still need a way to start the code on a raspberry pi.  Preferably without the need for a keyboard/mouse.  System service or something else?

**Comment by ryanvade** [comment]
Basic startup script was added with commit 1772e4f2

**Comment by ryanvade** [comment]
Light sensor in port 05 works.
