### ISSUE TITLE
Encoders are not working

### ISSUE THREAD

**Issue by ryanvade** [SIUE-SIGR/KIPR-Open#4]
We tried to test the encoders but could not get a response.  

A) What is the proper way of connecting them to a PSOC on the dev board?
B) Is there anything special that must be done before using them?

**Comment by BryanOrabutt** [comment]
Attach them to the encoder pins on the board. Pinout is the following
A0  GND  B0
A1  GND  B1

There is nothing special that needs done. The board has built in pull ups and the pinout of the PSoC is configured with code.

If using a dev board add 10K pull ups on signal pins. Center pin of the encoder's is GND, outer pins are signal pins. 
Encoder1: P2[6] & P2[4]
Encoder2: p2[5] & P2[3]

**Comment by ryanvade** [comment]
fixed with commit 7cf14a63a
